language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

script :
    - ./gradlew build connectedCheck    

notification:
  email:
    on_success: change
    on_failure: always